language: node_js
node_js:
    - 6.11.4

install:
    - ./scripts/setup

script:
    - ./scripts/lint

before_deploy:
    - ./scripts/cibuild

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_TOKEN
    file: 'tnc-network-site-${TRAVIS-TAG}.zip'
    skip-cleanup: true
    on:
        tags: true
        repo: CoastalResilienceNetwork/tnc-network-site
