#!/usr/bin/env bash
set -ex

function usage() {
    echo -n \
    "Usage: $(basename "$0")
Build application for staging or a release.
"
}

function cibuild() {
    if [ -z ${TRAVIS_TAG} ]
    then
        if [[ -n "${GIT_COMMIT}" ]]; then
            GIT_COMMIT="${GIT_COMMIT:0:7}"
        else
            GIT_COMMIT="$(git rev-parse --short HEAD)"
        fi
        zip -r tnc-network-site-${GIT_COMMIT}.zip src/
    else
        mv src/ tnc-network-site/
        zip -r tnc-network-site-${TRAVIS-TAG}.zip tnc-network-site/
    fi
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        cibuild
    fi
fi
